name: vemoir
description: A new Flutter project

environment:
  sdk: ">=3.5.4 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Make sure you have the latest version
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: 4.0.4
  path: ^1.9.1 
  camera: ^0.11.1
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  video_player: ^2.9.3
  shared_preferences: ^2.1.0
  video_thumbnail: ^0.5.3
  intl: ^0.20.2
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
